# This workflow builds the Sphinx documentation, and in doing so - checks for errors in the documentation.
name: docs

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    name: test docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip" # Cache the pip packages to speed up the workflow
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
      - name: Install Dependencies and Package
        run: uv sync --extra docs
      - name: Build Documentation
        run: |
          cd docs
          uv run sphinx-build -b html -j auto -a -n -T -W --keep-going . _build/html