name: lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  ruff:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get Ruff Version
        id: ruff-version
        run: echo "version=$(grep -Po '(?<=ruff==)[0-9]+\.[0-9]+\.[0-9]+' pyproject.toml)" >> $GITHUB_OUTPUT
  
      - uses: astral-sh/ruff-action@v3
        with:
          version: ${{ steps.ruff-version.outputs.version }}