name: lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get Ruff version
        id: ruff-version
        run: echo "version=$(grep -Po '(?<=ruff==)[0-9]+\.[0-9]+\.[0-9]+' pyproject.toml)" >> $GITHUB_OUTPUT

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          version: ${{ steps.ruff-version.outputs.version }}