# This test uses black and isort to check for code formatting issues.
name: Lint Checks

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:


jobs:
    black:
        name: Black Formatting Check
        runs-on: ubuntu-latest

        # Checkout the repository
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python 3.8
              uses: actions/setup-python@v5
              with:
                python-version: "3.8"
                cache: "pip" # Cache the pip packages to speed up the workflow

            - name: Install Dependencies and Project
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -U -r requirements.txt
                pip install -e .[dev]

            - name: Run Black Check
              run: |
                black --check --diff --verbose fortnite_api

    isort:
        name: Isort Formatting Check
        runs-on: ubuntu-latest

        # Checkout the repository
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python 3.8
              uses: actions/setup-python@v5
              with:
                python-version: "3.8"
                cache: "pip" # Cache the pip packages to speed up the workflow

            - name: Install Dependencies and Project
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install -U -r requirements.txt
                pip install -e .[dev]

            - name: Run Isort Check
              run: |
                isort --check --diff fortnite_api