name: release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dist:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/fortnite-api
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Build distributions
        run: uv build
      - name: Publish distributions
        run: uv publish