# This workflow will ensure that the pushed contents to the repo
# are not majorly breaking, and they comply with black standards.

name: Pychecking

on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel "coverage[toml]" pytest pytest-asyncio pytest-cov black
          pip install -U -r requirements.txt
          pip install -e .
      
      - name: Run Pytest Checks
        shell: bash
        run: |
          python -m pytest --cov=fortnite_api --import-mode=importlib -vs tests/

  black:
    name: Black Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel black
          pip install -U -r requirements.txt
          pip install -e .

      - name: Black Formatting Check 
        shell: bash
        run: |
          python -m black --check --verbose fortnite_api