# This workflow will ensure that the pushed contents to the repo
# are not majorly breaking, and they comply with black standards.

name: Pychecking

on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel "coverage[toml]" pytest pytest-asyncio
          pip install -U -r requirements.txt
      
      - name: Run tests
        shell: bash
        run: |
          python -m pytest tests/sync.py, tests/async.py -vs --import-mode=importlib
