# This workflow will ensure that the pushed contents to the repo
# are not majorly breaking.

name: Pytests

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
          cache: "pip" # Cache the pip packages to speed up the workflow

      - name: Install Dependencies and Package
        run: |
          python -m pip install -U pip setuptools
          pip install -U -r requirements.txt
          pip install -e .[tests]

      - name: Run Pytest Checks
        shell: bash
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
        run: python -m pytest --cov=fortnite_api --import-mode=importlib -vs tests/