name: test

on: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['3.8']
    
    name: pytest ${{ matrix.python-version }}
    steps:
      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel "coverage[toml]" pytest pytest-asyncio
        pip install -U requirements.txt
      
      - name: Run tests
      shell: bash
      run: |
        PYTHONPATH="&(pwd)" -m pytest tests/sync.py, tests/async.py -vs --import-mode=importlib
